# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Event Locator APP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Event Locator APP
    pod 'Parse'
    pod 'AFNetworking'



  target 'Event Locator APPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Event Locator APPUITests' do
    # Pods for testing
  end

end
